import type { Report } from '@/shared/types/reportTypes';

export const REPORT_DUMI: Report[] = [
  {
    accidentId: 'R001',
    user: { userId: 'U001', userName: '홍길동' },
    location: { latitude: 37.5665, longitude: 126.978 },
    accidentAt: '2025-08-28T08:30:00Z',
    deceleration: { decel: -8.2, startSpeed: 60, endSpeed: 5 },
    emergencyResponse: {
      emergencyNotified: true,
      familyNotified: true,
      reportedAt: '2025-08-28T08:32:00Z',
    },
    impulse: 120,
    scale: 'medium',
    drivingLogs: [
      {
        speed: 60,
        decelerationRate: -0.5,
        brakePedal: false,
        acceleratorPedal: true,
        timeOffsetSeconds: -10,
      },
      {
        speed: 40,
        decelerationRate: -6.0,
        brakePedal: true,
        acceleratorPedal: false,
        timeOffsetSeconds: -5,
      },
      {
        speed: 5,
        decelerationRate: -8.2,
        brakePedal: true,
        acceleratorPedal: false,
        timeOffsetSeconds: 0,
      },
    ],
  },
  {
    accidentId: 'R002',
    user: { userId: 'U002', userName: '김철수' },
    location: { latitude: 35.1796, longitude: 129.0756 },
    accidentAt: '2025-08-28T14:15:00Z',
    deceleration: { decel: -3.5, startSpeed: 50, endSpeed: 20 },
    emergencyResponse: {
      emergencyNotified: false,
      familyNotified: false,
      reportedAt: '2025-08-28T08:32:00Z',
    },
    impulse: 60,
    scale: 'medium',
    drivingLogs: [
      {
        speed: 50,
        decelerationRate: -0.3,
        brakePedal: false,
        acceleratorPedal: true,
        timeOffsetSeconds: -10,
      },
      {
        speed: 35,
        decelerationRate: -2.5,
        brakePedal: true,
        acceleratorPedal: false,
        timeOffsetSeconds: -5,
      },
      {
        speed: 20,
        decelerationRate: -3.5,
        brakePedal: true,
        acceleratorPedal: false,
        timeOffsetSeconds: 0,
      },
    ],
  },
  {
    accidentId: 'R003',
    user: { userId: 'U003', userName: '이영희' },
    location: { latitude: 37.4563, longitude: 126.7052 },
    accidentAt: '2025-08-28T19:40:00Z',
    deceleration: { decel: -7.0, startSpeed: 70, endSpeed: 10 },
    emergencyResponse: {
      emergencyNotified: true,
      familyNotified: false,
      reportedAt: '2025-08-28T19:42:00Z',
    },
    impulse: 95,
    scale: 'high',
    drivingLogs: [
      {
        speed: 70,
        decelerationRate: -1.0,
        brakePedal: false,
        acceleratorPedal: true,
        timeOffsetSeconds: -10,
      },
      {
        speed: 40,
        decelerationRate: -5.5,
        brakePedal: true,
        acceleratorPedal: false,
        timeOffsetSeconds: -5,
      },
      {
        speed: 10,
        decelerationRate: -7.0,
        brakePedal: true,
        acceleratorPedal: false,
        timeOffsetSeconds: 0,
      },
    ],
  },
  {
    accidentId: 'R004',
    user: { userId: 'U004', userName: '박민수' },
    location: { latitude: 36.3504, longitude: 127.3845 },
    accidentAt: '2025-08-28T11:05:00Z',
    deceleration: { decel: -2.0, startSpeed: 30, endSpeed: 25 },
    emergencyResponse: {
      emergencyNotified: false,
      familyNotified: true,
      reportedAt: '2025-08-28T08:32:00Z',
    },
    impulse: 20,
    scale: 'high',
    drivingLogs: [
      {
        speed: 30,
        decelerationRate: -0.2,
        brakePedal: false,
        acceleratorPedal: true,
        timeOffsetSeconds: -10,
      },
      {
        speed: 28,
        decelerationRate: -1.0,
        brakePedal: true,
        acceleratorPedal: false,
        timeOffsetSeconds: -5,
      },
      {
        speed: 25,
        decelerationRate: -2.0,
        brakePedal: true,
        acceleratorPedal: false,
        timeOffsetSeconds: 0,
      },
    ],
  },
  {
    accidentId: 'R005',
    user: { userId: 'U005', userName: '최지훈' },
    location: { latitude: 35.9078, longitude: 127.7669 },
    accidentAt: '2025-08-28T22:20:00Z',
    deceleration: { decel: -5.5, startSpeed: 55, endSpeed: 0 },
    emergencyResponse: {
      emergencyNotified: true,
      familyNotified: true,
      reportedAt: '2025-08-28T22:21:30Z',
    },
    impulse: 85,
    scale: 'high',
    drivingLogs: [
      {
        speed: 55,
        decelerationRate: -0.5,
        brakePedal: false,
        acceleratorPedal: true,
        timeOffsetSeconds: -10,
      },
      {
        speed: 30,
        decelerationRate: -4.0,
        brakePedal: true,
        acceleratorPedal: false,
        timeOffsetSeconds: -5,
      },
      {
        speed: 0,
        decelerationRate: -5.5,
        brakePedal: true,
        acceleratorPedal: false,
        timeOffsetSeconds: 0,
      },
    ],
  },
];
